dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.1
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
networks:
  default: development
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}